### ISSUE TITLE
Identify Brand Archtype

### ISSUE THREAD

**Issue by markszcz** [leonschu/njit-final-group-project#35]
I think we had a bunch of ideas here, just putting it down to reference back to.

I'm going to suggest we go with "The Ruler" archetype. The color Blue and Gold palette fits us very well. 
https://mylocalcollaborative.com/brand-blog-series-you-might-be-the-ruler-archetype-if/

Color palette idea
https://i.pinimg.com/736x/20/14/46/2014467e07b0a2f06c19f812757842c9.jpg

**Comment by leonschu** [comment]
The Ruler
